### ISSUE TITLE
KeyError: 'episode'

### ISSUE THREAD

**Issue by MaguraHiatus** [Jayapraveen/ITPro.Tv-Courses-downloader#18]
Been getting this Error after selecting Sub-category for Microsoft.

Traceback (most recent call last):
  File "C:\Users\Username\Desktop\ITPro.Tv-Courses-downloader-master\itprotv.py", line 148, in <module>
    episodes_download_links = get_download_links(episode_links,data_auth,resolution)
  File "C:\Users\Username\Desktop\ITPro.Tv-Courses-downloader-master\itprotv.py", line 109, in get_download_links
    if (req_data["episode"][resolution] == None):
KeyError: 'episode'

Need assistance

**Comment by wheseliip** [comment]
same error. any help ?

**Comment by Jayapraveen** [comment]
Fixed in commit (6966154)
