### ISSUE TITLE
Downloader not working ; something about video resolution 

### ISSUE THREAD

**Issue by dexter101010** [Jayapraveen/ITPro.Tv-Courses-downloader#25]
ITPro.Tv-Courses-downloader-master>python itprotv.py
Token is Valid!

0 Get Started
1 Most Popular
2 CompTIA
3 Microsoft
4 Cisco
5 Security Skills
6 Linux
7 (ISC)²
8 EC-Council
9 Python
10 Apple
11 AWS
12 VMware
13 ITIL®
14 Google
15 Agile
16 CertNexus
17 Service Management
18 Project Management
19 PMI®
20 PRINCE2®
21 Big Data
22 GIAC
23 ISACA
24 Governance
25 Six Sigma
26 Automation
27 Networking Skills
28 Foundation Skills
29 Cloud Technology Skills
30 Virtualization Skills
31 OfficeProTV
32 DevProTV
33 Podcasts
34 Webinars
35 Business Skills
36 Legacy

Enter your choice: 4
0 Cisco CCT Routing and Switching (100-490)
1 Cisco CCNA (200-301)
2 Cisco CyberOps Associate (200-201)
3 Cisco Certified DevNet Associate (200-901)
4 Cisco CCNP Enterprise ENCOR (350-401)
5 Cisco CCNP Enterprise ENSLD (300-420)
6 Cisco CCNP Enterprise ENARSI (Exam 300-410)
7 Cisco CCNP Security SCOR (Exam 350-701)
8 Cisco CCNP Security SNCF (Exam 300-710)
9 Cisco CCNP Data Center DCCOR (350-601)
10 Hands-on with Cisco Meraki Wireless Access Points
11 Hands-on with Cisco Modeling Labs 2 (CML2)

Enter your choice: 9
0 Overview
1 An NX-OS Primer
2 OSPFv2 dccor
3 OSPFv3
4 MP-BGP
5 PIM
6 FHRPs
7 RSTP+
8 LACP dccor
9 vPC dccor
10 VXLAN
11 EVPN
12 OTV
13 What is Cisco ACI
14 The Cisco APIC
15 ACI Access Policies
16 ACI VMM
17 ACI Tenant Policies
18 ACI Contracts and Microsegmentation
19 Packet Flow Analysis
20 NIST 800-145 Cloud Defined
21 Nexus Software Updates
22 Nexus Configuration Management
23 NetFlow
24 SPAN
25 Streaming Telemetry
26 UCS Rack Servers
27 UCS Blade Chassis
28 UCS Initial Setup
29 UCS Infrastructure Management
30 UCS Network Management
31 UCS Storage Management
32 UCS Monitoring
33 HyperFlex Infrastructure
34 UCS Software Updates
35 UCS Backup and Restore
36 SPAN in the UCS
37 Intersight
38 Fibre Channel
39 Port Channels
40 Switched Fabric Initialization
41 VSANs
42 FCoE Unified Fabric
43 NFS and NAS
44 Monitoring and Software Updates
45 EEM
46 Scheduler
47 User Interface Options
48 JSON and XML
49 Ansible
50 Puppet
51 Python
52 POAP
53 DCNM and UCSD
54 AAA and RBAC
55 First Hop Security
56 CoPP
Total= 57
Traceback (most recent call last):
  File "itprotv.py", line 148, in <module>
    episodes_download_links = get_download_links(episode_links,data_auth,resolution)
  File "itprotv.py", line 109, in get_download_links
    if (req_data["episode"][resolution] == None):
KeyError: 'episode'

**Comment by thisismyrepo** [comment]
I'm getting this same error

**Comment by amleshjha** [comment]
same here.

**Comment by kris96** [comment]
They changed the URL for episodes so change the URL on line 98 (itprotv.py) from 
`episode_url = f"https://api.itpro.tv/api/urza/v3/consumer-web/brand/{brand_itpro}/episode?url="`
to
`episode_url = f"https://app.acilearning.com/api/urza/v3/consumer-web/episode?url="`
and it should work

**Comment by jamesbabiak** [comment]
> They changed the URL for episodes so change the URL on line 98 (itprotv.py) from `episode_url = f"https://api.itpro.tv/api/urza/v3/consumer-web/brand/{brand_itpro}/episode?url="` to `episode_url = f"https://app.acilearning.com/api/urza/v3/consumer-web/episode?url="` and it should work

THANK YOU!

For anyone still trying to get this work, this simple change fixes the script even now (9/2025).

The 250 monthly download limit through the webpage was making me mad :).
