### ISSUE TITLE
retry not defined

### ISSUE THREAD

**Issue by DenisSlobodyanyuk** [Jayapraveen/ITPro.Tv-Courses-downloader#9]
Traceback (most recent call last):
  File "****/ITPro.Tv-Courses-downloader-master/itprotv.py", line 142, in <module>
    download_video(url,filename)
  File "****/ITPro.Tv-Courses-downloader-master/itprotv.py", line 67, in download_video
    download_video(url,filename, epoch + 1)
  File "****/ITPro.Tv-Courses-downloader-master/itprotv.py", line 52, in download_video
    if (epoch > retry):
NameError: name 'retry' is not defined

**Comment by Jayapraveen** [comment]
Fixed in commit (324f3c1).
